[tool.poetry]
name = "securedrop-export"
version = "0.0.0"
description = "SecureDrop Qubes export scripts"
authors = ["SecureDrop Team"]
license = "GPLv3+"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pexpect = "^4.9.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.15.0"
types-setuptools = "^80.8.0"
pytest = "^8.3.5"
pytest-cov = "^6.1.1"
pytest-mock = "^3.14.1"
semgrep = "^1.122.0"
types-pexpect = "^4.9.0.20250516"
pygobject-stubs = "*"

[tool.mypy]
python_version = "3.11"
