[tool.poetry]
name = "securedrop-export"
version = "0.0.0"
description = "SecureDrop Qubes export scripts"
authors = ["SecureDrop Team"]
license = "GPLv3+"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pexpect = "^4.9.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.0"
types-setuptools = "^69.5.0"
pytest = "^8.2.0"
pytest-cov = "^5.0.0"
pytest-mock = "^3.14.0"
semgrep = "^1.71.0"
types-pexpect = "^4.9.0.20240311"

[tool.mypy]
python_version = "3.11"
