---
common-steps:
  - &install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        set -e
        apt update && apt install -y git gnupg libarchive13 libmagic1 libqt5x11extras5 make python3-tk python3-dev gnupg python3-venv sqlite3 xvfb

  - &configure_locales
    run:
      name: Configure locales
      command: |
        set -e
        apt update && apt install -y locales
        echo "en_US ISO-8859-1" >> /etc/locale.gen
        echo "en_US UTF-8" >> /etc/locale.gen
        locale-gen

  - &configure_locales
    run:
      name: Configure locales
      command: |
        set -e
        apt update && apt install -y locales
        echo "en_US ISO-8859-1" >> /etc/locale.gen
        echo "en_US UTF-8" >> /etc/locale.gen
        locale-gen

  - &install_build_dependencies
    run:
      name: Install build dependencies
      command: |
        set -e
        apt update && apt install -y git make sudo

  - &run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-random

  - &run_integration_tests
    run:
      name: Install requirements and run integration tests
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-integration

  - &run_functional_tests
    run:
      name: Install requirements and run functional tests
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-functional

  - &run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make check-black check-isort lint mypy

  - &check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make semgrep bandit

  - &check_source_strings
    run:
      name: Check that source strings are updated
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make check-strings

  - &check_mo_repro
    run:
      name: Check that translation machine objects are reproducible
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make verify-mo

  - &check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make safety

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download Python wheels
      command: |
        set -x
        mkdir ~/packaging && cd ~/packaging
        # local builds may not have an ssh url, so || true
        git config --global --unset url.ssh://git@github.com.insteadof || true
        git clone https://github.com/freedomofpress/securedrop-builder.git
        cd securedrop-builder
        apt-get update && apt-get install -y sudo make
        make install-deps
        PKG_DIR=~/project make requirements

  - &check_packaging_requirements
    run:
      name: Ensure that the same Python requirements are used for packaging and production.
      command: |
        cd ~/project
        # Fail if unstaged changes exist that are not comments (after `make requirements` in the previous run step).
        git diff --ignore-matching-lines=# --exit-code

  - &check_testing_requirements
    run:
      name: Ensure that the same Python requirements are used for development/testing and production.
      command: |
        set -e
        export VERSION_CODENAME=$(~/project/scripts/codename)
        make venv
        source .venv/bin/activate
        make requirements
        git diff --exit-code requirements/dev-${VERSION_CODENAME}-requirements.txt

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/project
        ./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here
        cd ~/packaging/securedrop-builder
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        make securedrop-client

version: 2.1

jobs:
  build:
    parameters: &parameters
      image:
        type: string
    docker: &docker
      - image: debian:<< parameters.image >>
    steps:
      - *install_build_dependencies
      - checkout
      - *install_packaging_dependencies
      - *check_packaging_requirements
      - *build_debian_package

  unit-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - *configure_locales
      - checkout
      - *run_unit_tests
      - store_test_results:
          path: test-results

  integration-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *run_integration_tests

  functional-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *run_functional_tests

  lint:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *run_lint

  check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_security

  check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_python_dependencies_for_vulnerabilities


  check-internationalization:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_source_strings
      - *check_mo_repro

  check-testing-requirements:
    parameters: *parameters
    docker: *docker
    steps:
      - *install_testing_dependencies
      - checkout
      - *check_testing_requirements

workflows:
  securedrop_client_ci:
    jobs: &jobs
      - unit-test:
          matrix: &matrix
            parameters:
              image:
                - bullseye
                - bookworm
      - integration-test:
          matrix: *matrix
      - functional-test:
          matrix: *matrix
      - lint:
          matrix: *matrix
      - check-testing-requirements:
          matrix: *matrix
      - check-security:
          matrix: *matrix
      - check-python-security:
          matrix: *matrix
      - check-internationalization:
          matrix: *matrix
      - build:
          matrix: *matrix

  nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *jobs
