---
common-steps:
  - &run_tests
    run:
      name: Install requirements and run tests
      command: |
        set -e
        virtualenv .venv
        source .venv/bin/activate
        pip install --require-hashes -r dev-requirements.txt
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make check --keep-going

  - &check_python_dependencies_for_vulns
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        source .venv/bin/activate
        make safety

  - &run_static_analysis
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        source .venv/bin/activate
        make bandit

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download wheels
      command: |
        mkdir ~/packaging && cd ~/packaging
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        make install-deps && make fetch-wheels
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &make_source_tarball
    run:
      name: Tag and make source tarball
      command: |
        cd ~/project
        ./update_version.sh 1000.0  # Dummy version number, doesn't matter what we put here
        python3 setup.py sdist

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=/home/circleci/project/dist/securedrop-client-$PKG_VERSION.tar.gz
        make securedrop-client

version: 2
jobs:
  build-stretch:
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout
      - *install_packaging_dependencies
      - *verify_requirements
      - *make_source_tarball
      - *build_debian_package

  build-buster:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - *install_packaging_dependencies
      - *verify_requirements
      - *make_source_tarball
      - *build_debian_package

  test-stretch:
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout
      - run: sudo apt-get install -y sqlite3 libqt5x11extras5
      - *run_tests
      - *check_python_dependencies_for_vulns
      - *run_static_analysis

  test-buster:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run: sudo apt-get install -y sqlite3 libqt5x11extras5
      - *run_tests
      - *check_python_dependencies_for_vulns
      - *run_static_analysis

workflows:
  version: 2
  securedrop_client_ci:
    jobs:
      - test-stretch
      - build-stretch
      - test-buster
      - build-buster
