version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install requirements and run tests
          command: |
            pipenv install --keep-outdated --dev
            export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
            pipenv run make check --keep-going

      - run:
          name: Check Python dependencies for known vulnerabilities
          command: pipenv check

      - run:
          name: Run static analysis on source code to find security issues
          command: pipenv install --keep-outdated --dev bandit && pipenv run bandit --recursive . -ll
