---
common-steps:
  - &run_tests
    run:
      name: Install requirements and run tests
      command: |
        apt-get update && apt-get install -y make python3-venv
        make venv
        source .venv/bin/activate
        make check

  - &install_packaging_dependencies
    run:
      name: Install Debian packaging dependencies and download wheels
      command: |
        apt-get update && apt-get install -y git git-lfs make sudo
        mkdir ~/packaging && cd ~/packaging
        git clone https://github.com/freedomofpress/securedrop-debian-packaging.git
        cd securedrop-debian-packaging
        make install-deps
        PKG_DIR=~/project make requirements

  - &verify_requirements
    run:
      name: Ensure that build-requirements.txt and requirements.txt are in sync.
      command: |
        cd ~/project
        # Return 1 if unstaged changes exist (after `make requirements` in the
        # previous run step), else return 0.
        git diff --quiet

  - &build_debian_package
    run:
      name: Build debian package
      command: |
        cd ~/packaging/securedrop-debian-packaging
        export PKG_VERSION=1000.0
        export PKG_PATH=~/project/
        make securedrop-log

version: 2
jobs:
  test-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *run_tests

  build-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *install_packaging_dependencies
      - *verify_requirements
      - *build_debian_package

workflows:
  version: 2
  per_pr:
    jobs:
      - test-bullseye
      - build-bullseye
