version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install requirements and run tests
          command: |
            set -e
            pipenv sync --dev
            export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
            pipenv run make check

      - run:
          name: Check Python dependencies for known vulnerabilities
          command: pipenv check

      - run:
          name: Run static analysis on source code to find security issues
          command: |
            set -e
            pipenv install --keep-outdated --ignore-pipfile --dev bandit
            pipenv run bandit --recursive . -ll
