[advisories]
# advisory IDs to ignore e.g. ["RUSTSEC-2019-0001", ...]
ignore = [
    "RUSTSEC-2025-0134" # rustls-pemfile is unmaintained (#2893)
]

# Output Configuration
[output]
deny = ["warnings"]
quiet = false

# Target Configuration
[target]
arch = "x86_64" # Ignore advisories for CPU architectures other than this one
os = "linux" # Ignore advisories for operating systems other than this one
