[tool.black]
line-length = 100

[tool.isort]
line_length = 100

[tool.poetry]
name = "securedrop-proxy"
version = "0.1.0"
description = "Qubes RPC proxy service for the SecureDrop Client"
authors = ["SecureDrop Team"]
license = "GPLv3+"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
pyyaml = "^5.4.1"
requests = "^2.31.0"

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
coverage = "^7.3.0"
flake8 = "^6.1.0"
isort = "^5.12.0"
mypy = "^1.5.1"
types-PyYAML = "^6.0.12.11"
types-requests = "^2.31.0.2"
vcrpy = "^5.1.0"
bandit = "*"
safety = "*"
